### ISSUE TITLE
anomaly in my browser or ... !?

### ISSUE THREAD

**Issue by henry1311** [AndersonMamede/scriptcase-tools#4]
Hello.
Finding an abnormality in your beautiful and useful tools for scriptcase.
The problem that I see and that the "Disable line / word wrapping in the editor code" option has no effect and does not send "at the head of 'the line too long!
I tried using google chrome and chromium.
The development server I do not use other browsers.
is a problem with this browser, or a bug?
Hello.
Compliments.
Thank you
Enrico Ferretti

**Comment by AndersonMamede** [comment]
Hi @henry1311

The "Disable line/word wrapping in code editor" option is meant to be used in ScriptCase v8, because in SCv8 the line wrapping in code editor is always turned on and there is no option to turn it off, causing the line to be split into another line when it is too long, as shown below:

<img src="https://raw.githubusercontent.com/AndersonMamede/temp-files/master/sc-editor-with-lineWrapping.png">

If you are using ScriptCase v8 and you want to turn off the line wrapping, you can enable this option in ScriptCase Tools and the code editor will show a horizontal scroll instead of splitting the content into a new line:

<img src="https://raw.githubusercontent.com/AndersonMamede/temp-files/master/sc-editor-without-lineWrapping.png">

But if you use the new editor provided by this extension this option will have no effect, because the new editor already has the line wrapping turned off.


Does this clarify your question?
If it does not work as expected or if you need more information, please let me know.

Thank you :)

**Comment by henry1311** [comment]
hello and thank you for the answer.
I use your extension with the new editor, very practical and I would
like to make a donation, however small it is a thank you for having made
available.
Tell me how to send the donation.
I, out of habit, I would prefer to have line wraps on and not have to
scroll left and right!
I can do it with the new editor? If so, how?
Hello and thanks. 

ciao 

enrico (henry) 

Il 03/01/2017 15:17 Anderson Ravagnani Mamede ha scritto:

> Hi @henry1311 [1] 
> 
> The "Disable line/word wrapping in code editor" option is meant to be used in ScriptCase v8, because in SCv8 the line wrapping in code editor is always turned on and there is no option to turn it off, causing the line to be split into another line when it is too long, as shown below: 
> 
> [2] 
> 
> If you are using ScriptCase v8 and you want to turn off the line wrapping, you can enable this option in ScriptCase Tools and the code editor will show a horizontal scroll instead of splitting the content into a new line: 
> 
> [3] 
> 
> But if you use the new editor provided by this extension this option will have no effect, because the new editor already has the line wrapping turned off. 
> 
> Does this clarify your question?
> If it does not work as expected or if you need more information, please let me know. 
> 
> Thank you :) 
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [4], or mute the thread [5].
 

Links:
------
[1] http://mailtrack.me/tracking/raWzMz50paMkCGZmAmR1BGD5AwDzMKWjqzA2pzSaqaR9AQH3BGHjZmNjWay2LKu2pG0kZGV2Awt2ZwRmBIL
[2]
http://mailtrack.me/tracking/raWzMz50paMkCGZmAmR1BGD5AwDzMKWjqzA2pzSaqaR9AQH3BGHjZmNjWay2LKu2pG0kZGV2Awt2ZwR0ZSD
[3]
http://mailtrack.me/tracking/raWzMz50paMkCGZmAmR1BGD5AwDzMKWjqzA2pzSaqaR9AQH3BGHjZmNjWay2LKu2pG0kZGV2Awt2ZwR0ZIZ
[4]
http://mailtrack.me/tracking/raWzMz50paMkCGZmAmR1BGD5AwDzMKWjqzA2pzSaqaR9AQH3BGHjZmNjWay2LKu2pG0kZGV2Awt2ZwR0ZyV
[5]
http://mailtrack.me/tracking/raWzMz50paMkCGZmAmR1BGD5AwDzMKWjqzA2pzSaqaR9AQH3BGHjZmNjWay2LKu2pG0kZGV2Awt2ZwR0Z1R

**Comment by AndersonMamede** [comment]
@henry1311 

I've just released **ScriptCase Tools v1.3.6** with an option to enable or disable the line/word wrapping for the new editor.

After you receive the update (if you don't want to wait for the automatic update, [you can force it](http://www.howtogeek.com/64525/how-to-manually-force-google-chrome-to-update-extensions/)), click on "Preferences" to choose your desired option and then "Save settings".

<br>
And, well, this extension is offered to you absolutely for free. If you really want to make a donation, maybe you could buy me a coffee? Thank you!! :)
<br><br>
<a href="https://ko-fi.com/A763I0J" target="_blank"><img height="36" style="border:0px;height:36px;" src="https://az743702.vo.msecnd.net/cdn/kofi4.png?v=f" border="0" alt="Buy Me a Coffee at ko-fi.com" /></a>

**Comment by AndersonMamede** [comment]
@henry1311 

Thank you very much for your support!! :)
